# Build docker images and push them to DockerHub
# Reference: https://github.com/marketplace/actions/build-and-push-docker-images

name: build-push

on:
  push:
    branches:
      - main
    paths:
      - "docker/hello-world/*/**"
      - ".github/workflows/build-push.yml"
  workflow_dispatch:
  
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push \#1
        uses: docker/build-push-action@v3
        with:
          context: ./docker/hello-world/echo
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2022-sast-hello:echo

      - name: Build and push \#2
        uses: docker/build-push-action@v3
        with:
          context: ./docker/hello-world/build-basic
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2022-sast-hello:basic

      - name: Build and push \#3
        uses: docker/build-push-action@v3
        with:
          context: ./docker/hello-world/build-slim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2022-sast-hello:slim

      - name: Build and push \#4
        uses: docker/build-push-action@v3
        with:
          context: ./docker/hello-world/build-env
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2022-sast-hello:env
