
name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git remote add gitlab 'https://liang2kl:${{ secrets.GITLAB_TOKEN }}@gitlab.com/liang2kl/2022-summer-training-docker-tutorial'
          git push gitlab --force
